#!/bin/zsh
alias caw="cal -w"
alias artisan="php artisan"
alias serve="artisan serve"
alias horizon="artisan horizon"
alias lz="lazygit"

#Laradock stuff
alias laradock="cd ~/Projects/PHP/laradock"
alias startwork="laradock; sudo docker-compose up -d nginx workspace redis"
alias stopwork="laradock; sudo docker-compose down"

function laradock-manage(){
    current_dir=$PWD;
    laradock;
    sudo docker-compose $*;
    cd $current_dir;
}

function shell(){
    current_dir=${PWD##*/}
    current_dir_path=$PWD
    if [[ $# == 0 ]]
    then
        laradock; sudo docker-compose exec --user=laradock workspace bash -c "cd $current_dir && bash -l" && cd $current_dir_path
    else
        laradock; sudo docker-compose exec --user=laradock workspace bash -c "cd $current_dir && bash -l -c '$*'" && cd $current_dir_path
    fi
}

function shell_root(){
    current_dir=${PWD##*/}
    current_dir_path=$PWD
    if [[ $# == 0 ]]
    then
        laradock; sudo docker-compose exec workspace bash -c "cd $current_dir && bash -l" && cd $current_dir_path
    else
        laradock; sudo docker-compose exec workspace bash -c "cd $current_dir && bash -l -c '$*'" && cd $current_dir_path
    fi
}

if [ -f ~/.git-flow_aliases ]; then
    . ~/.git-flow_aliases
fi

if [ -f ~/.rits_aliases ]; then
    . ~/.rits_aliases
fi

if [ -f ~/.work_aliases ]; then
    . ~/.work_aliases
fi


if [ -f ~/.wsl_aliases ]; then
    . ~/.wsl_aliases
fi
